kind: Namespace
apiVersion: v1
metadata:
  name: octopusdb
---
kind: Namespace
apiVersion: v1
metadata:
  name: staging-octopus
---
kind: Namespace
apiVersion: v1
metadata:
  name: production-octopus
---
kind: Namespace
apiVersion: v1
metadata:
  name: gitness
---
kind: Namespace
apiVersion: v1
metadata:
  name: registry
---
kind: Namespace
apiVersion: v1
metadata:
  name: ingress
---
kind: Namespace
apiVersion: v1
metadata:
  name: monitoring
---
kind: Namespace
apiVersion: v1
metadata:
  name: argocd
