apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: staging-octopus
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJob3N0LmRvY2tlci5pbnRlcm5hbDozMDUwMCI6eyJ1c2VybmFtZSI6ImJwY2xvdWRyZXBvc2l0b3J5IiwicGFzc3dvcmQiOiJLaWFzdTEyMyEiLCJhdXRoIjoiWW5CamJHOTFaSEpsY0c5emFYUnZjbms2UzJsaGMzVXhNak1oIn19fQ==
