apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: staging-octopus
  name: octopus-role-staging
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get"]
